
import __ASTRO_IMAGE_IMPORT_1j4cls from "../../assets/profile-pictures/Dave_Barry.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FDave_Barry.md";
import __ASTRO_IMAGE_IMPORT_1qYhC1 from "../../assets/profile-pictures/Graeme_Ball.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FGraeme_Ball.md";
import __ASTRO_IMAGE_IMPORT_1s3JVH from "../../assets/profile-pictures/Laura_Murphy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FLaura_Murphy.md";
import __ASTRO_IMAGE_IMPORT_MtBGn from "../../assets/profile-pictures/Marie_Held.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FMarie_Held.md";
import __ASTRO_IMAGE_IMPORT_2mJn0X from "../../assets/profile-pictures/Stefania_Marcotti.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FStefania_Marcotti.md";
import __ASTRO_IMAGE_IMPORT_ZDSUhr from "../../assets/profile-pictures/Stephen_Cross.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FStephen_Cross.md";
import __ASTRO_IMAGE_IMPORT_1kOnYs from "../../assets/profile-pictures/portrait_placeholder.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FZ_More.md";
export default new Map([["../../assets/profile-pictures/Dave_Barry.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FDave_Barry.md", __ASTRO_IMAGE_IMPORT_1j4cls], ["../../assets/profile-pictures/Graeme_Ball.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FGraeme_Ball.md", __ASTRO_IMAGE_IMPORT_1qYhC1], ["../../assets/profile-pictures/Laura_Murphy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FLaura_Murphy.md", __ASTRO_IMAGE_IMPORT_1s3JVH], ["../../assets/profile-pictures/Marie_Held.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FMarie_Held.md", __ASTRO_IMAGE_IMPORT_MtBGn], ["../../assets/profile-pictures/Stefania_Marcotti.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FStefania_Marcotti.md", __ASTRO_IMAGE_IMPORT_2mJn0X], ["../../assets/profile-pictures/Stephen_Cross.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FStephen_Cross.md", __ASTRO_IMAGE_IMPORT_ZDSUhr], ["../../assets/profile-pictures/portrait_placeholder.png?astroContentImageFlag=&importer=src%2Fcontent%2Fbios%2FZ_More.md", __ASTRO_IMAGE_IMPORT_1kOnYs]]);
		